---
title: "Artifical Intelligence"
---

You might be familiar with Artificial Intelligence (AI) tools such as ChatGPT, Gemini, Copilot, and Grammarly. These tools can be beneficial in academic contexts when used appropriately to support your learning. Appropriate uses include:

-   Improving the quality of your writing, e.g. correcting grammar
-   Identifying sources of information
-   Summarising notes
-   Organising tasks

However, there are drawbacks to using AI tools that you should be aware of. It is also not appropriate to use AI tools as a substitute for your own work when completing assessments. More detail on these points is given below.

### Limitations of AI

Whilst AI can generate plausible-sounding responses, there are a number of limitations and ethical considerations that may impact both academic and professional integrity. As with indiscriminate use of Google and Wikipedia, inappropriate use of AI may potentially impede development of critical analysis and the learning process through:

-   Inaccuracy and bias: AI draws from information that may be out-of-date or inaccurate, and can be affected by historical bias, prejudice, and content maliciously fed into the model.

-   Generating false responses: AI models do not discriminate between fake and real content, and may also fabricate plausible-sounding material that does not really exist.

-   Lack of context: AI models often don't understand nuance, and are unfamiliar with the wider course content.

-   Privacy and security concerns: Uploading data to AI models presents a risk of data breaches, and may compromise ethical standards (e.g. participant confidentiality).

You can mitigate the impact of these concerns by being aware of the limitations of AI. The golden rule is that **you should use AI tools to aid learning, not to replace learning**. For instance, you could:

-   use it to correct your grammar, rather than to write your essay

-   ask it to suggest sources of information (which you can then verify), rather than to do your research for you

### Using AI for assessments

You should be aware that inappropriate use of AI might be considered an [academic offence](https://plymouthpsychology.github.io/handbooks/academic_dishonesty.html). When you submit an assessment, you are declaring that it is your work. Unless you have been instructed to use generative AI for your assessment, submitting content generated by an AI tool is not permitted and may be regarded as plagiarism, misrepresentation, or fabrication. This applies to all forms of assessment, e.g. essays, practical reports, and presentations.

Some assessments might include a reflective component. Reflections are intended to be a personal and authentic representation of your thoughts, learning experiences, and insights. Reflective practice is considered essential for psychology professionals, as demonstrated within professional and regulatory standards (e.g. BPS, HCPC). Using AI to generate your reflection not only undermines the aim of reflection in the first place (learning, development, gaining of specific knowledge/skills etc.) but is also regarded as a professionalism issue.

### Useful information

The library guide for student use of AI can be found [here](https://plymouth.libguides.com/c.php?g=708948&p=5113535).
