---
title: "Apprenticeships"
---

Apprenticeships are short, voluntary projects that students can participate in alongside staff in the School. The School offers two kinds of apprenticeships: research apprenticeships, and EDI apprenticeships. Information on both is presented below.

### Research apprenticeships

The Research Apprentice scheme has been developed by The School of Psychology to let students gain research experience during the academic year. The goal of the scheme is to provide an educational experience to students in any stage of the psychology programmes by exposing them to the process of conducting cutting-edge research in "learning by doing." Students can volunteer to work on a research project under the supervision of a member of academic staff.

The scheme is unpaid, and entirely voluntary. Apprenticeships typically consist of 4 hours per week, for ten weeks.

While the apprenticeship is totally separate from the final year project, it can provide useful experience and expertise. Students need to check with staff members who they would like to work with whether they are willing to accept students. Upon completion of the scheme students will receive a letter from the Head of School documenting their participation. For further information, please contact Dr. Liam Cross: [liam.cross\@plymouth.ac.uk](mailto:liam.cross@plymouth.ac.uk){.email}

How to become a Research Apprentice:

1.  Identify some possible Supervisors. Use the school web pages or your knowledge from lectures to find out which staff research the areas of psychology you are interested in working in. Do some background research by reading papers they have published recently.

2.  Find out if your potential supervisors are looking for apprentices this academic year. Send them an email or visit them during their office hours, or check advertised apprenticeship opportunities here: <https://www.psy.plymouth.ac.uk/apps/apprentice/>

### EDI apprenticeships

The School of Psychology is committed to creating an environment where we celebrate diversity, where everyone feels included and where everyone is treated equally. We are taking a leading role in Equality, Diversity, and Inclusion (EDI) in the University with projects such as the Red Box scheme, which initially launched in our school, and in shaping the Extenuating Circumstances policy.

The goal of the EDI Apprenticeship Scheme is to provide a learning experience to undergraduate students, by giving them an opportunity to carry out a piece of work supporting EDI in our school under the supervision of a staff member.

If you are interested, look at the apprenticeship opportunities which are advertised. These are based around projects that we are currently working on in the school. We are always open to new projects too and we would be delighted to talk to you about any ideas you have: <https://www.psy.plymouth.ac.uk/apps/apprentice/>

The scheme is entirely voluntary and typically consists of about 8 hours work. Students who complete an apprenticeship will be asked to complete a piece such as a video clip or blog documenting their work. They will also be awarded a £50 in thanks for their contribution. You can see some of the work done by previous EDI apprentices [here](https://liveplymouthac-my.sharepoint.com/:f:/g/personal/clare_walsh_plymouth_ac_uk/Ejd-n3iweG1El_BEgxNzDukBOwUtHIJmxFlocBossxM5SA?e=Rr5ezD).
