---
title: "Group Work"
---

All our programmes include at least some modules that require students to work together in groups. There are lots of reasons why we do this, including:

-   Working in groups allows students to achieve things that wouldn't be possible alone. For instance, group work is typically used where students are conducting research. Research is only meaningful if the data are adequate to address the research question, and groups of students can collect adequate samples much more easily than individual students could.

-   Learning often works best when we collaborate with one another. Some of the components of the research process might be challenging at first for some students, and working together provides an opportunity to help each other develop skills and gain confidence using them.

-   Almost all of you will go on to careers that require you to work with other people. It's important that you have opportunities to practise working collaboratively. Teamwork is a skill that, like other skills, requires practice.

However, some of you might find group work challenging. There might be times when you find it frustrating or unfair, and module staff will do what they can to help. Some of our processes for supporting you are outlined here.

### Group allocations

We have consulted with students at length on the best way to allocate students to groups. We have different procedures for Stage 1 and Stage 2 modules, as described here. These approaches have been decided by directly polling students to see which of various approaches is preferred, talking to student representatives, and reading comments from module evaluations.

Stage 1: In workshops, you will work in your tutorial groups. This allows you to get to know the people you will be working with throughout the year, and means that nobody needs to worry about starting the year not knowing anybody to form a group with.

Stage 2: We will allocate you to project groups randomly. This gives you an opportunity to meet and work with new people, which is good practice for working in different groups later in your careers. If there is a substantial issue that requires a change of project group, please contact the module leader.

Some of you might wonder why we don't allow students to choose their own groups. Self-selection is inherently unfair, as some students find it hard to form groups with other people; perhaps because of personality, or disability, or commitments outside university. We think the fairest and most inclusive approach is to allocate you to groups. It is also better practice for later in your careers, as very few of you will be able to choose to work exclusively with your friends.

### Ensuring engagement and managing problems

All students are expected to fully engage with group work and module requirements. This means attending all timetabled lectures and workshops, conducting the additional reading, and contributing to the group assignment (e.g. designing the study, preparing documents for ethical review, collecting data, designing the poster, and presenting).

One of the pitfalls of group work is that it can encourage freeriding, which is when some group members put in less effort on the assumption that others will pick up the slack. We manage this in two ways.

The first is that we actively monitor and interact with each group. You will be expected to attend workshops to work together, and we will monitor attendance and talk to you about whether there are any group members who are not contributing adequately. To help us catch and deal with problems as early as possible, you can tell us in the workshops if there are people in your group who are not contributing adequately. We will first contact those people to try to resolve the issue and make sure everybody can contribute. If problems persist, we may remove students with poor engagement from a group.

The second is that we will take account of engagement in our marking processes. For example, if a student attends a group poster presentation without having participated fully in the work up to that point, we may award that student a lower mark than the rest of their group. Similarly, if a student submits a research report using data generated by their group, without having participated adequately in the collection of the data, then this will be reflected in the mark they receive.

If any student is having problems with their group, they should talk to a member of module staff during a workshop so we can try to resolve the issue as quickly as possible.
