---
title: "Psylab"
---

Psylab is our interactive learning facility. It is also a method of assessment. Several modules contain Psylab as an integral part of their teaching.

The main component of Psylab is a website, which we use to administer tasks. These tasks are part of the assessment for each module that includes Psylab. The workshop and laboratory space located in Link 301 contains flexible work space, equipment, and laptops that you can borrow to complete tasks.

The Psylab website can be accessed via the School's Technical Office homepage: <https://www.psy.plymouth.ac.uk/home/>

When you log in to the website, you will see a list of items for your modules. Each one is an interactive activity that has been designed to further your understanding of a topic on that module, and to give you the opportunity to experience it for yourself.

### Stage 1 and 2 Psylab assessment

In Stage 1, Psylab is part of two modules: PSYC421 and PSYC424. In Stage it is part of PSYC523 and PSYC524. You will be able to complete tasks in sequence during each module, and they are intended to help support your learning. Each task is worth a certain number of marks, which will be specified by the module leader.

For each of these modules, the Psylab tasks are worth 10% of the module mark in total. You should ensure that all tasks are completed by the deadline at the end of the module.

### Stage 4 Psylab assessment

In Stage 4, Psylab is a pass/fail assessment for PSYC605. This means that you must complete a certain number of tasks to pass the module. Psylab does not contribute directly to your module mark, which is determined by other assessments. However, if you do not complete enough Psylab tasks then you will fail the module and your module mark may therefore be capped if you pass at a later date. We do not expect students who are engaged with the course to fail the Psylab element of any module.

In order to mark an activity as completed, you need to finish it before the deadline. This is the same as the dissertation deadline.

Once this deadline has passed, we will count the number of activities you have completed. The module has a criterion for passing, i.e. a number of activities that must be completed that is specified on the module information. If you do not meet this requirement, you will fail the module.

If you're unsure about what you need to do, contact either the module lead or your personal tutor.
