---
title: "Tutorials and Briefings"
---

As well as completing the modules that make up your programme, all students in the School participate in a series of tutorials designed to support your academic and professional development. These differ by year of study, and are described briefly below.

It's important to note that tutorials are not on your timetable and will be arranged by your personal tutor.

For more on personal tutors, [go here](https://plymouthpsychology.github.io/handbooks/personal_tutors.html). To find out who your personal tutor is, check the "Tutor Groups" system on the [School's internal web page](https://www.psy.plymouth.ac.uk/home/).

Students in Stage 1 and Stage 2 also have weekly briefings to support their study, described below.

## Stage 1

Stage 1 students have two group tutorials in Semester 1. These are small-group sessions arranged by your tutor, with only the members of your tutorial group (perhaps eight of you) present. Your tutor will contact you to arrange these. You should expect one to take place in the first week of the semester, and the other to take place around the fifth week.

Stage 1 students also have progress meetings with tutors at three points in the year: once at the end of Semester 1, and twice during Semester 2. These might be one-on-one, though you can meet your tutor in small groups of two or three if you prefer. Your tutor will contact you to arrange these.

There are also weekly briefings. These are Zoom meetings for the whole cohort, usually at 10am on Mondays. These work a bit like school assemblies, and provide information about what's happening on the course and more widely in the School. They are intended to help you keep on top of what's going on, as well as to tell you about additional resources and events. Briefings are also a great place to ask questions using the chat function, which we will answer directly towards the end of the session.

The Zoom link for briefings will be posted on the [programme DLE page](https://dle.plymouth.ac.uk/course/view.php?id=38727), in the "Tutorial information" section).

## Stage 2

Stage 2 students have a group tutorial in the third week of Semester 1, by arrangement with tutors. Students also meet tutors for progress meetings three times: once towards the end of Semester 1, and twice in Semester 2. As in Stage 1, these meetings can be one-on-one or can be held in small groups of two or three if you prefer. Your tutor will contact you to arrange these.\

Stage 2 students also have weekly briefings, as in Stage 1. These will usually be at 11am on Mondays. The Zoom link to access the briefings can be found on the [programme DLE page](https://dle.plymouth.ac.uk/course/view.php?id=38727), in the "Tutorial information" section.

## Stage 4

Stage 4 students have a group tutorial in the fourth week of Semester 1, by arrangement with tutors. Students also meet tutors for progress meetings three times: once towards the end of Semester 1, and twice in Semester 2. As in Stage 1, these meetings can be one-on-one or can be held in small groups of two or three if you prefer. Your tutor will contact you to arrange these.
